# Generated by Django 3.0.7 on 2023-02-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20230203_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='vino_no',
            new_name='vin_no',
        ),
    ]
